### ISSUE TITLE
Haxelib git doesn't work (source path?)

### ISSUE THREAD

**Issue by jcward** [jcward/lazy-props#5]
Is it possible to specify source path? Or must we move LazyProps.hx to the root dir?

**Comment by skial** [comment]
I think this is the haxelib git command format - `haxelib git <project-name> <git-clone-path> <branch> <subdirectory>`, so `haxelib git lazyprops https://github.com/jcward/lazy-props.git master src` should work. 

I haven't tested this yet.

**Comment by skial** [comment]
The command format was taken from http://old.haxe.org/doc/haxelib/using_haxelib

**Comment by jcward** [comment]
Awesome, thanks for the info. I'll give that a try.
